spring:
  profiles:
    active:
      - test

logging:
  level:
    root: INFO
    org.springframework: INFO
    io.github.ivanrosw.fakerest: INFO

server:
  port: 8450

management:
  endpoints:
    web:
      exposure:
        include: mappings

---
spring:
  config:
    activate:
      on-profile: test

rest:
  controllers:
    -
      uri: '/test/{id}/{id2}'
      method: GET
    -
      uri: '/test/{id}/{id2}'
      method: POST
      generateId: true
      generateIdPatterns:
        id: UUID
    -
      uri: '/test2/{id}'
      method: GET
      answer: '{"id":"1","data":"value"}'
    -
      uri: '/test2/{id}'
      method: POST
    -
      uri: '/test2/{id}'
      method: PUT
    -
      uri: '/test2/{id}'
      method: DELETE
    -
      uri: '/test3'
      method: POST
  routers:
    -
      uri: '/test'
      toUrl: '/test/'
      method: GET
    -
      uri: '/test'
      toUrl: '/test/'
      method: POST